# Generated by Django 4.0.5 on 2022-07-01 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('project_description', models.TextField()),
                ('img_path', models.CharField(max_length=200)),
                ('github_link', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
