# Generated by Django 4.0.5 on 2022-07-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects_site', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
