# Generated by Django 4.0.5 on 2022-10-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_site', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language',
            field=models.CharField(default='Python', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='replit_link',
            field=models.CharField(default='https://replit.com/@BenSpeakman1', max_length=200),
        ),
    ]
