# Generated by Django 4.0.5 on 2022-10-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_site', '0003_project_language_project_replit_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='language_icon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='language',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
