# Generated by Django 4.0.5 on 2022-10-03 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_site', '0004_project_language_icon_alter_project_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='website_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
